server:
  port: 8888

spring:
  application:
    name: weather
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3333}/${DB_NAME:weather_db}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5000}

weather:
  token: ${WEATHER_API_TOKEN:2f621196f60e4635b45161439241212}
  api-url: ${WEATHER_API_URL:https://api.weatherapi.com/v1}
